FROM alpine:latest
ARG no_proxy=169.254,bitbucket.bip.uk.fid-intl.com
RUN apk update all && apk add py-pip openjdk11-jdk jq git zip unzip curl maven coreutils openssl
RUN pip install boto3 awscli && pip install --upgrade setuptools && pip install cfn-lint
#RUN pip install awscli
#RUN pip install --upgrade setuptools
# RUN pip install cf
RUN apk add --no-cache bash && apk add --update sed
RUN mkdir /.aws && chmod -R 777 /.aws && git config --global http.sslVerify false
#RUN chmod -R 777 /.aws
#RUN git config --global http.sslVerify false

ENTRYPOINT ["/bin/sh"]
